language: bash

sudo: true

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - os: osx

install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
        sudo apt-get --no-install-recommends -qq install rng-tools
    fi

script:
  - bash --version
  - source bash-funk.sh && -test-all
